#!/bin/bash

## https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeo pipefail

commit=$(git rev-parse --short=16 HEAD)

if [ "$PREVIOUS" != "true" ]; then
    echo "Building re-find $commit"
    rm -rf out
    if [ "$LOCAL_DEPS" = "true" ]; then
        clojure -A:local-deps:build-simple
    else
        clojure -A:build-simple
    fi
fi

echo "Preparing deploy folder"
rm -rf dist
mkdir -p dist/js
cp out/main.js "dist/js/main-$commit.js"
mkdir -p dist/css
cp resources/public/css/style.css "dist/css/style-$commit.css"
cp resources/public/prod.html dist/index.html
sed -i.bak "s/\$COMMIT/$commit/g" dist/index.html
rm "dist/index.html.bak"

if [ "$DEPLOY" = "true" ]; then
    echo "Copying to server"
    ssh borkdude@michielborkent.nl "rm -rf re-find.web; mkdir -p re-find.web"
    scp -r dist/* borkdude@eetvoorjeleven.nu:re-find.web
elif [ "$PREVIEW" = "true" ]; then
    echo "Previewing app"
    cd dist && python -m SimpleHTTPServer
fi
