#!/bin/bash

rm -rf out
commit=$(git rev-parse --short=16 HEAD)
echo "Building re-find $commit"
clojure -A:build-simple

echo "Preparing deploy folder"
rm -rf /tmp/re-find.web
mkdir -p /tmp/re-find.web/js
cp out/main.js "/tmp/re-find.web/js/main-$commit.js"
mkdir -p /tmp/re-find.web/css
cp resources/public/css/style.css "/tmp/re-find.web/css/style-$commit.css"
cp resources/public/prod.html /tmp/re-find.web/index.html
sed -i -e "s/\$COMMIT/$commit/g" /tmp/re-find.web/index.html
rm "/tmp/re-find.web/index.html-e"

if [ $PREVIEW ]; then
  echo "Previewing app"
  cd /tmp/re-find.web && python -m SimpleHTTPServer
else
  echo "Copying to server"
  ssh borkdude@michielborkent.nl "rm -rf re-find.web; mkdir -p re-find.web"
  scp -r /tmp/re-find.web/* borkdude@eetvoorjeleven.nu:re-find.web              
fi
